services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    ports:
      - '80:8080'
      - '443:8443'
    env_file:
      - .env
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /data/database.sqlite
    volumes:
      - storage:/app/storage
      - database:/data
      - logos:/app/public/images/companies
      - certs:/certs
    restart: unless-stopped

volumes:
  storage:
  database:
  logos:
  certs:
