services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-8080}:80'
      - '${APP_HTTPS_PORT:-8443}:443'
    env_file:
      - .env
    environment:
      DB_DATABASE: /data/database.sqlite
      APP_URL: ${APP_URL:-http://localhost:${APP_PORT:-8080}}
      SSL_MODE: ${SSL_MODE:-none}
      CERTBOT_EMAIL: ${CERTBOT_EMAIL:-}
      RUN_MIGRATIONS: true
    volumes:
      - storage:/app/storage
      - database:/data
      - logos:/app/public/images/companies
      - certs:/certs
    restart: unless-stopped

volumes:
  storage:
  database:
  logos:
  certs:
